Register-Tool @{
    ID          = 'AD-059'
    Name        = 'AD Test Lab Builder'
    Category    = 'AD'
    Description = 'Instructions and script to build AD test lab'
    DangerLevel = 'Moderate'
    ConfirmMessage = 'Generate AD test lab build script?'
    ServerOnly  = $true
    ClientOnly  = $false
    Action      = {
        try {
            $output = Join-Path $env:TEMP "AD-TestLab-$(Get-Date -Format yyyyMMdd-HHmmss)"
            New-Item -ItemType Directory -Path $output -Force | Out-Null
            Write-Color "`n  ─── AD TEST LAB BUILDER ───" "Cyan"
            Write-Color "  This generates PowerShell scripts to build an AD test lab using Hyper-V" "Cyan"
            Write-Color "`n  ─── Lab Configuration ───" "Cyan"
            $domainName = Read-Host "Lab domain name (default: lab.contoso.com)"
            if (-not $domainName) { $domainName = "lab.contoso.com" }
            $dcName = Read-Host "DC VM name (default: LAB-DC1)"
            if (-not $dcName) { $dcName = "LAB-DC1" }
            $clientName = Read-Host "Client VM name (default: LAB-CL1, blank to skip)"
            $vSwitchName = Read-Host "Hyper-V Virtual Switch name (default: LabInternal)"
            if (-not $vSwitchName) { $vSwitchName = "LabInternal" }
            $labScript = @"
# AD Test Lab Builder - Generated by AD-059
# ============================================
# Run this script on a Hyper-V host

`$domainName = "$domainName"
`$dcName = "$dcName"
`$vSwitchName = "$vSwitchName"
`$clientName = "$clientName"
`$adminPass = Read-Host "Enter DSRM/admin password" -AsSecureString
`$isoPath = Read-Host "Path to Windows Server ISO (e.g., D:\ISO\WS2022.iso)"
`$vhdxPath = "$env:TEMP\LabVMs"

Write-Host "[*] Creating AD Test Lab Environment" -ForegroundColor Cyan

# 1. Create virtual switch
if (-not (Get-VMSwitch -Name `$vSwitchName -ErrorAction SilentlyContinue)) {
    New-VMSwitch -Name `$vSwitchName -SwitchType Internal
    Write-Host "[+] Virtual switch created: `$vSwitchName" -ForegroundColor Green
}

# 2. Create VHDX directories
`$dcVhdx = Join-Path `$vhdxPath "`$dcName.vhdx"
if (-not (Test-Path `$vhdxPath)) { New-Item -ItemType Directory -Path `$vhdxPath -Force | Out-Null }

# 3. Create DC VM
Write-Host "[*] Creating DC VM: `$dcName" -ForegroundColor Cyan
New-VM -Name `$dcName -MemoryStartupBytes 4GB -BootDevice VHD -Generation 2 -SwitchName `$vSwitchName -Path `$vhdxPath
New-VHD -Path `$dcVhdx -SizeBytes 60GB -Dynamic
Add-VMHardDiskDrive -VMName `$dcName -Path `$dcVhdx
Add-VMDvdDrive -VMName `$dcName -Path `$isoPath
Set-VMFirmware -VMName `$dcName -EnableSecureBoot Off -FirstBootDevice (Get-VMDvdDrive -VMName `$dcName)
Set-VMProcessor -VMName `$dcName -Count 2
Enable-VMIntegrationService -VMName `$dcName -Name "Guest Service Interface"
Start-VM -Name `$dcName

Write-Host "[+] DC VM created and started" -ForegroundColor Green

if (`$clientName) {
    `$clientVhdx = Join-Path `$vhdxPath "`$clientName.vhdx"
    New-VM -Name `$clientName -MemoryStartupBytes 2GB -BootDevice VHD -Generation 2 -SwitchName `$vSwitchName -Path `$vhdxPath
    New-VHD -Path `$clientVhdx -SizeBytes 40GB -Dynamic
    Add-VMHardDiskDrive -VMName `$clientName -Path `$clientVhdx
    Start-VM -Name `$clientName
    Write-Host "[+] Client VM created and started: `$clientName" -ForegroundColor Green
}

Write-Host "`n=== POST-INSTALLATION STEPS ===" -ForegroundColor Cyan
Write-Host "1. Connect to DC VM via Hyper-V Manager or VMConnect" -ForegroundColor White
Write-Host "2. Set Admin password and configure networking:" -ForegroundColor White
Write-Host "   IP: 192.168.100.10/24, Gateway: 192.168.100.1, DNS: 127.0.0.1" -ForegroundColor Gray
Write-Host "3. Install AD DS and promote:" -ForegroundColor White
Write-Host "   Install-WindowsFeature AD-Domain-Services -IncludeManagementTools" -ForegroundColor Gray
Write-Host "   Install-ADDSForest -DomainName `$domainName -SafeModeAdministratorPassword (ConvertTo-SecureString '...' -AsPlainText -Force)" -ForegroundColor Gray
Write-Host "4. Reboot, then create test OUs and users:" -ForegroundColor White
Write-Host "   New-ADOrganizationalUnit -Name 'Users'" -ForegroundColor Gray
Write-Host "   New-ADUser -Name 'TestUser1' -SamAccountName 'tuser1' -UserPrincipalName 'tuser1@`$domainName' -AccountPassword (ConvertTo-SecureString 'P@ssw0rd' -AsPlainText -Force) -Enabled `$true" -ForegroundColor Gray
Write-Host "5. Join client to domain if created" -ForegroundColor White
"@
            $labScriptPath = Join-Path $output "Create-ADTestLab.ps1"
            $labScript | Out-File -FilePath $labScriptPath -Encoding UTF8
            Write-Color "  [+] Lab build script: $labScriptPath" "Green"
            Write-Color "`n  ─── Lab Design Overview ───" "Cyan"
            Write-Color "  Domain: $domainName" "White"
            Write-Color "  DC: $dcName (192.168.100.10)" "White"
            Write-Color "  Switch: $vSwitchName (192.168.100.0/24)" "White"
            Write-Color "  DNS: DC will serve DNS for the domain" "White"
            if ($clientName) { Write-Color "  Client: $clientName (DHCP from DC)" "White" }
            Write-Color "`n  ─── Additional Guidance ───" "Cyan"
            Write-Color "  Configure NAT on Hyper-V host for internet access:" "White"
            Write-Color "  New-NetNat -Name LabNat -InternalIPInterfaceAddressPrefix 192.168.100.0/24" "Gray"
            Write-Color "  Install DHCP on DC for automatic client IP assignment:" "White"
            Write-Color "  Install-WindowsFeature DHCP; Add-DhcpServerV4Scope -Name Lab -StartRange 192.168.100.20 -EndRange 192.168.100.200 -SubnetMask 255.255.255.0" "Gray"
            Write-Color "`n  [i] All files saved to: $output" "Green"
        } catch {
            Write-Color "  [!] AD Test Lab Builder failed: $_" "Red"
        }
        Pause
    }
}
