Register-Tool @{
    ID          = 'AD-058'
    Name        = 'AD Backup to Azure'
    Category    = 'AD'
    Description = 'Configure backup upload script for Azure Blob'
    DangerLevel = 'Moderate'
    ConfirmMessage = 'Configure AD backup script for Azure Blob upload?'
    ServerOnly  = $true
    ClientOnly  = $false
    Action      = {
        try {
            Write-Color "`n  ─── AD BACKUP TO AZURE ───" "Cyan"
            $configPath = Join-Path $env:ProgramData "MaddixSuite\AD-AzureBackup.json"
            Write-Color "  [*] This tool generates a scheduled backup script for AD System State to Azure Blob Storage" "Cyan"
            Write-Color "`n  ─── Configuration ───" "Cyan"
            $storageAccount = Read-Host "Azure Storage Account Name"
            $containerName = Read-Host "Container Name (default: ad-backups)"
            if (-not $containerName) { $containerName = "ad-backups" }
            $sasToken = Read-Host "SAS Token (leave blank to use AzCopy login)"
            $backupDir = Read-Host "Local temp directory (default: C:\ADBackupTemp)"
            if (-not $backupDir) { $backupDir = "C:\ADBackupTemp" }
            $retentionDays = Read-Host "Local retention days (default: 7)"
            if (-not $retentionDays) { $retentionDays = 7 }
            $dc = (Get-ADDomainController -Filter * | Select-Object -First 1).Name
            $scriptContent = @"
# AD Backup to Azure Blob - Generated by AD-058
# Schedule: Windows Task Scheduler - Daily
`$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
`$backupDir = "$backupDir"
`$containerName = "$containerName"
`$storageAccount = "$storageAccount"
`$sasToken = "$sasToken"
`$retentionDays = $retentionDays
if (-not (Test-Path `$backupDir)) { New-Item -ItemType Directory -Path `$backupDir -Force | Out-Null }
Write-Host "[*] Starting AD System State backup..." -ForegroundColor Cyan
try {
    `$dc = Get-ADDomainController -Filter * | Select-Object -First 1
    Write-Host "[i] DC: `$(`$dc.Name)" -ForegroundColor Gray
    `$backupPath = Join-Path `$backupDir "ADBackup-`$timestamp"
    New-Item -ItemType Directory -Path `$backupPath -Force | Out-Null
    Write-Host "[*] Running Windows Server Backup..." -ForegroundColor Cyan
    `$wbParams = @{
        BackupTarget = `$backupPath
        SystemState = `$true
        Quiet = `$true
        IncludeCritical = `$true
    }
    try {
        Get-WBJob -ErrorAction SilentlyContinue | Where-Object `$_.CurrentStatus -eq 'Running' | Stop-WBJob -Force -ErrorAction SilentlyContinue
    } catch {}
    `$policy = New-WBPolicy
    `$ss = Get-WBSystemState
    Add-WBSystemState -Policy `$policy
    `$target = New-WBBackupTarget -VolumePath `$backupPath
    Add-WBBackupTarget -Policy `$policy -Target `$target
    Start-WBBackup -Policy `$policy -Async
    do {
        `$job = Get-WBJob -ErrorAction SilentlyContinue
        Write-Host "[*] Backup progress: $(if(`$job.CurrentStatus -eq 'Running'){'Running...'}else{`$job.CurrentStatus})" -ForegroundColor Yellow
        Start-Sleep -Seconds 10
    } while (`$job.CurrentStatus -eq 'Running')
    Write-Host "[+] System State backup completed" -ForegroundColor Green
    `$backupFile = Join-Path `$backupDir "AD-SystemState-`$timestamp.zip"
    Compress-Archive -Path `$backupPath -DestinationPath `$backupFile -Force
    Write-Host "[+] Archive created: `$backupFile" -ForegroundColor Green
    Remove-Item -Path `$backupPath -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "[*] Uploading to Azure Blob..." -ForegroundColor Cyan
    if (`$sasToken) {
        `$url = "https://`$storageAccount.blob.core.windows.net/`$containerName/AD-SystemState-`$timestamp.zip`$sasToken"
        `$destUrl = "https://`$storageAccount.blob.core.windows.net/`$containerName/AD-SystemState-`$timestamp.zip"
        if (Get-Command azcopy -ErrorAction SilentlyContinue) {
            & azcopy copy "`$backupFile" "`$destUrl`$sasToken" --overwrite=true
        } else {
            `$storageContext = New-AzStorageContext -StorageAccountName `$storageAccount -SasToken `$sasToken -ErrorAction Stop
            Set-AzStorageBlobContent -File `$backupFile -Container `$containerName -Context `$storageContext -Blob "AD-SystemState-`$timestamp.zip" -Force -ErrorAction Stop | Out-Null
        }
    } else {
        & azcopy copy "`$backupFile" "https://`$storageAccount.blob.core.windows.net/`$containerName/AD-SystemState-`$timestamp.zip" --overwrite=true
    }
    Write-Host "[+] Upload complete" -ForegroundColor Green
    Get-ChildItem `$backupDir -Filter "AD-SystemState-*.zip" | Where-Object { `$_.LastWriteTime -lt (Get-Date).AddDays(-`$retentionDays) } | Remove-Item -Force -ErrorAction SilentlyContinue
    Write-Host "[+] Old backups cleaned up (retention: `$retentionDays days)" -ForegroundColor Green
} catch {
    Write-Host "[!] Backup/Azure upload failed: `$_" -ForegroundColor Red
    exit 1
}
"@
            $scriptPath = Join-Path $env:ProgramData "MaddixSuite\AD-BackupToAzure.ps1"
            $configDir = Split-Path $scriptPath -Parent
            if (-not (Test-Path $configDir)) { New-Item -ItemType Directory -Path $configDir -Force | Out-Null }
            $scriptContent | Out-File -FilePath $scriptPath -Encoding UTF8
            Write-Color "  [+] Backup script created: $scriptPath" "Green"
            Write-Color "`n  ─── Scheduled Task Setup ───" "Cyan"
            $createTask = Read-Host "Create scheduled task to run daily at 2 AM? (y/n)"
            if ($createTask -eq 'y') {
                $taskName = "AD-Backup-To-Azure"
                $action = New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$scriptPath`""
                $trigger = New-ScheduledTaskTrigger -Daily -At "02:00AM"
                $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
                $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
                Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description "AD System State backup to Azure Blob Storage" -Force
                Write-Color "  [+] Scheduled task '$taskName' created" "Green"
                Write-Color "  [i] Runs daily at 2:00 AM as SYSTEM" "Gray"
            }
            Write-Color "`n  ─── Prerequisites ───" "Cyan"
            Write-Color "  - Windows Server Backup feature: Install-WindowsFeature Windows-Server-Backup" "White"
            Write-Color "  - AzCopy: https://aka.ms/downloadazcopy" "White"
            Write-Color "  - Or Azure PowerShell: Install-Module Az.Storage" "White"
            Write-Color "  - Azure Blob container '$containerName' must exist" "White"
        } catch {
            Write-Color "  [!] AD Backup to Azure setup failed: $_" "Red"
        }
        Pause
    }
}
