Register-Tool @{
    ID          = 'AD-027'
    Name        = 'Samba AD Linux Integration'
    Category    = 'AD'
    Description = 'Show Samba AD join instructions, generate join script'
    DangerLevel = 'Safe'
    ConfirmMessage = 'Show Samba AD Linux integration info and generate join script?'
    ServerOnly  = $true
    ClientOnly  = $false
    Action      = {
        try {
            Write-Color "  [*] Samba AD Linux Integration" "Cyan"
            $domain = (Get-ADDomain -ErrorAction SilentlyContinue).DNSRoot
            if (-not $domain) { $domain = "yourdomain.local" }

            Write-Color "" "Gray"
            Write-Color "  ─── Linux Samba AD Join Steps ───" "Cyan"
            Write-Color "" "Gray"
            Write-Color "  Debian/Ubuntu:" "White"
            Write-Color "    sudo apt-get install samba winbind krb5-user" "Gray"
            Write-Color "    sudo samba-tool domain join $domain DC -U Administrator" "Gray"
            Write-Color "" "Gray"
            Write-Color "  RHEL/Fedora/CentOS:" "White"
            Write-Color "    sudo dnf install samba samba-winbind krb5-workstation" "Gray"
            Write-Color "    sudo net ads join -U Administrator" "Gray"
            Write-Color "" "Gray"
            Write-Color "  Standalone Samba AD (new domain):" "White"
            Write-Color "    sudo samba-tool domain provision --domain=maddix --adminpass=Passw0rd" "Gray"
            Write-Color "    (This does NOT require Windows AD)" "Gray"
            Write-Color "" "Gray"

            $choice = Read-Host "  [?] Generate Samba AD join script? (y/N)"
            if ($choice -eq 'y') {
                $joinScript = @"
#!/bin/bash
# Samba AD Join Script - Generated by MaddixSuite
DOMAIN="$domain"
echo "Joining $DOMAIN as DC..."
sudo apt-get update
sudo apt-get install -y samba winbind krb5-user
sudo samba-tool domain join $DOMAIN DC -U Administrator
echo "Done. Reboot recommended."
"@
                $outPath = "$env:TEMP\samba-join.sh"
                $joinScript | Set-Content -Path $outPath -Encoding UTF8
                Write-Color "  [+] Script saved: $outPath" "Green"
                Write-Color "  [i] Copy to Linux and run: bash samba-join.sh" "Gray"
            }
        } catch {
            Write-Color "  [!] Samba integration failed: $_" "Red"
        }
        Pause
    }
}
